package com.rnd.baseproject.retrofit_api.response


data class User(
    var id: Int,
    var first_name: String,
    var last_name: String,
    var phone_number: String,
    var email: String,
    var profile_image: String,
    var country_id: Int,
    var token: String,
    var associative_id: Int,
    var is_phone_verified: Int,
    var is_email_verified: Int,
    var email_verified_at: String,
    var phone_number_verified_at: String,
    var is_gps: Int,
    var is_active: Int,
    var is_deleted: Int,
    var is_blocked: Int,
    var is_registered: Int,
    var is_account_verified: Int,
    var has_subscription: Int,
    var created_by: Long,
    var updated_by: Long,
    var deleted_by: Long,
    var created_on: Long,
    var updated_on: Long,
    var deleted_on: Long,
    var adhar_image: String,
    var area_name: String,
    var city_id: Int,
    var otp: Int,
    var category_name: String,
    var url_path: String,
    var referral_code: String,
    var is_profile_image: Int,
    var image_path: String,
)
/**{
"id": 4,
"first_name": "Drashti",
"last_name": "Prajapati",
"phone_number": "9313791429",
"email": "",
"profile_image": "",
"token": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiMzE5NWUzOGM4MTlmZmM4MDI0YTQxYTA2NThkMjQ3NDA3MjQ2MTYxY2Y4MzU1ZDA0OTRiNjg1NzIzMWY3YTFhYzgyMjk5MzBhZDkwNzFhN2IiLCJpYXQiOjE2ODQzODU1NDAuODA0NTM4LCJuYmYiOjE2ODQzODU1NDAuODA0NTQxLCJleHAiOjE3MTYwMDc5NDAuODAzMzg2LCJzdWIiOiI0Iiwic2NvcGVzIjpbXX0.eeP8kq1bGyTQI5jioAAp4fW-Ki2nrZ_OiZ_TZG1ulTRjUu1h3fYaM-n2rD62Tbr6ZNKwakt_tGgTyBtcWl7L9JP29rIVFn3fBJFZMBQJ-Y1Lv9Lgpyha452JB80XC02F4BGmJ5zdu_jVp5EAASh4POyoTa_-zOyUz-d5EelhpCUU4uz8foNSKCb3euMJ6wYsIBmHUmLfbtqL4ULDoj2ro2eAiouk4eRtF97DR2aBVdsCGDCIUrbPwPGi0sZB1HZpGAL03H7isZGkXcbgnnDXJTcmEhg2p_EAe8ecDXBAMI9F29rp0_diT-yLv-FCrkOQpBz7is9nfts23Bqe5O1EegbTPLQGcMH1tB9LFGVZ1nofyJOIOFyjXXJIX2XrkC_ZqGV65A8P2oHKEXQhXBtUeTvEo85q1HdZp5Lx21x-XOmd6llOI84zNfnlxxs5Wj5rb4iwuHk4t0E3t3SU0hMPPofoTzTdbN7-ulP7qsOHjZdIag7YkaQkkhx-701rNubcUDGU-cZMlllTs25zuVXbA6DLY0y5GZFrCDkiwbpDkRaTJKiww8-B3UlB_Ub80n-dd7wJ9N5T8sfD8DZZdvTMHXFu2kXn-xqX0Ccsuk-z07GRIrdL-KSwb4WKiI7OvgpLanAoNZXAzIFj_JTEynbTuXhLsWt5ZV93T4EI1FRgBHo",
"associative_id": 1,
"is_phone_verified": 1,
"is_email_verified": 0,
"email_verified_at": "2023-05-18T04:52:21.155097Z",
"phone_number_verified_at": "",
"is_gps": 0,
"is_active": 1,
"is_deleted": 0,
"is_blocked": 0,
"is_registered": 1,
"is_account_verified": 0,
"has_subscription": 1,
"created_by": 0,
"updated_by": 4,
"deleted_by": 0,
"created_on": 1681273874,
"updated_on": 1683982530,
"deleted_on": 0,
"country_id": 91,
"adhar_image": "adhar-632757124116Kutchch.jpg",
"area_name": "Nikol",
"city_id": 470,
"otp": 953736,
"category_name":"Electrician"
}*/